### ISSUE TITLE
How to "Download" data back from C14 archive

### ISSUE THREAD

**Issue by hareemca** [scaleway/c14-cli#22]
Reviewing the commands below:
There seems to be no command to download data back from C14 Archive

Commands:
    create    Create a new archive
    files     List the files of an archive
    freeze    Lock an archive
    help      Help of the c14 command line
    login     Log in to Online API
    ls        List the archives
    rename    Rename an archive
    remove    Remove an archive
    unfreeze  Unlock an archive
    upload    Upload your file or directory into an archive

**Comment by Solvik** [comment]
the unfreeze command take the data back from C14 and put it on a temporary space accessible via sftp

**Comment by hareemca** [comment]
Isn't sftp really slow ?
