### ISSUE TITLE
Issue removing archive

### ISSUE THREAD

**Issue by Matthiew** [scaleway/c14-cli#43]
Hello 
I've got some trouble about removing old archive. (older than a month)
When I run the command **c14 remove** I've got this warning

> WARN[0000] xxxxx: Archive xxxxx not found

But when I'm using the web interface I can remove the concerned archive without any problem

What could be the problem? 

Thanks
Matthieu

**Comment by sicardf** [comment]
+1

**Comment by t0k4rt** [comment]
Same issue.
Sometimes it works, sometimes it doesn't.
Actually I don't understand your product. There is no documentation, no explaination, no support.

**Comment by t0k4rt** [comment]
What I tried and got:
* when I try to remove archive yyy, I get `Archive yyy not found`
* when I launch unfreeze on archive xxx , then I launch remove archive on yyy, it works.

Neither verbose nor debug mode do anything when calling:
`c14 -D remove yyyyy`

**Comment by t0k4rt** [comment]
@agirot Hi, is anyone from online reading issues ?
