### ISSUE TITLE
Caching of Archives appears to be broken

### ISSUE THREAD

**Issue by Daverball** [scaleway/c14-cli#46]
I was seeing strange behaviour with the c14-cli utility whenever I tried to have multiple buckets open and tried interacting with the newly created ones.

The online console was showing these archives with a ready temporary storage and was providing ssh authentication data that worked when entered manually, but the c14-cli utility would insist that the archive didn't exist.

Looking more closely at the source code I noticed that all of these commands were calling `FindSafeUUIDFromArchive` with `useCache` set to `true`, a quick and dirty patch, setting all of these calls to `false` resolved all of the issues I was facing.

The `c14 upload` command already seems to fall back to not using the cache automatically but the `c14 bucket` command does not, which I used to check if the bucket was ready, since bucket creation isn't instant even after the archive has been created using `c14 create` from what I could tell. At least I did get error messages of missing archives every so often with the upload command until I changed the script I had written to wait for the bucket to be returned with the `c14 bucket` command.

Generally the `c14 bucket` command seems to have been left in the dust a bit, since you have to use the uuid to refer to the archive rather than its given name like with all the other commands and the missing fallback to not using the cache.

That being said however I do believe the caching mechanism is not working as intended and is the issue at heart, since even after an entire day of waiting the command would still report the archive as missing, no matter what I tried, like running `c14 ls` or other commands.

I suspect that elements do not get added to the cache properly and are overwriting previous entries rather than being appended since the one archive that would work no matter what was always the oldest one, which was lowest in the ls command.

**Comment by alpagap** [comment]
I wanted to open an issue for this one, the problem is the cache creates a new map for each "safe", so the previous one is lost
I have created a PR for this
