### ISSUE TITLE
ansible module ?

### ISSUE THREAD

**Issue by nerzhul** [scaleway/c14-cli#7]
Hello, the CLI was written in GoLang, this is nice, but is there a project to add ansible modules support ? Could be very very great to manage C14 backups like S3/Glacier in ansible

Thanks

**Comment by moul** [comment]
Hi @nerzhul, great idea, do you have some links to existing solution in which we can get inspiration from?

**Comment by nerzhul** [comment]
Hi @moul , you will find interesting cloud modules for ansible there

https://github.com/ansible/ansible-modules-core/tree/devel/cloud/amazon

Each module is a single python file which can call external modules/commands

**Comment by topkool** [comment]
+1

**Comment by topkool** [comment]
+1
